baseURL = 'https://www.leberjs.dev'
languageCode = 'en-us'
defaultContentLanguage = "en"

theme = "hermit-v2"
copyright = "Jason Leber"
enableRobotsTXT = true

[author]
    name = "Jason Leber"

[languages]
  [languages.en]
    title = "Jason Leber"
    [languages.en.params]
        homeSubtitle = "Wannabe Go developer. Aspiring Architect. All around curious."

[params]
    description = "leberjs personal site"
    title = "leberjs.dev"
    dateFormat = "2023-01-02"

    [[params.socialLinks]]
        name = "email"
        url = "mailto:leberjs@gmail.com"

    [[params.socialLinks]]
        name = "github"
        url = "https://github.com/leberjs"

[menu]
    
    [[menu.main]]
        name = "Bytes"
        url = "bytes/"
        weight = 10

    [[menu.main]]
        name = "Posts"
        url = "posts/"
        weight = 10
