baseURL = 'http://leberjs.dev'
languageCode = 'en-us'
title = 'leberjs.dev'

theme = "hugo-bearcub"
copyright = "Jason Leber"
enableRobotsTXT = true

[author]
    name = "Jason Leber"

[params]
    dateFormat = "2023-01-02"

    [social]
        email = "leberjs@gmail.com"
